// Code generated by tygo. DO NOT EDIT.

//////////
// source: api_key.go

export interface ApiKeyCreate {
  name: string;
  expiresAt: string;
}
export interface ApiKeyCreated {
  name: string;
  key: string;
  createdAt: string;
  expiresAt: string;
}

//////////
// source: deployment.go

export interface DeploymentRead {
  id: string;
  name: string;
  type: string;
  ownerId: string;
  zone: string;
  createdAt: string;
  updatedAt?: string;
  repairedAt?: string;
  restartedAt?: string;
  accessedAt: string;
  cpuCores: number /* float64 */;
  ram: number /* float64 */;
  replicas: number /* int */;
  url?: string;
  envs: Env[];
  volumes: Volume[];
  initCommands: string[];
  args: string[];
  private: boolean;
  internalPort: number /* int */;
  image?: string;
  healthCheckPath?: string;
  customDomain?: string;
  customDomainUrl?: string;
  customDomainStatus?: string;
  customDomainSecret?: string;
  status: string;
  error?: string;
  replicaStatus?: ReplicaStatus;
  pingResult?: number /* int */;
  /**
   * Integrations are currently not used, but could be used if we wanted to add a list of integrations to the deployment
   * For example GitHub
   */
  integrations: string[];
  teams: string[];
  storageUrl?: string;
}
export interface DeploymentCreate {
  name: string;
  cpuCores?: number /* float64 */;
  ram?: number /* float64 */;
  replicas?: number /* int */;
  private: boolean;
  envs: Env[];
  volumes: Volume[];
  initCommands: string[];
  args: string[];
  image?: string;
  healthCheckPath?: string;
  /**
   * CustomDomain is the domain that the deployment will be available on.
   * The max length is set to 243 to allow for a subdomain when confirming the domain.
   */
  customDomain?: string;
  /**
   * Zone is the zone that the deployment will be created in.
   * If the zone is not set, the deployment will be created in the default zone.
   */
  zone?: string;
}
export interface DeploymentUpdate {
  name?: string;
  cpuCores?: number /* float64 */;
  ram?: number /* float64 */;
  replicas?: number /* int */;
  private?: boolean;
  envs?: Env[];
  volumes?: Volume[];
  initCommands?: string[];
  args?: string[];
  image?: string;
  healthCheckPath?: string;
  /**
   * CustomDomain is the domain that the deployment will be available on.
   * The max length is set to 243 to allow for a subdomain when confirming the domain.
   */
  customDomain?: string;
}
export interface Env {
  name: string;
  value: string;
}
export interface Volume {
  name: string;
  appPath: string;
  serverPath: string;
}
export interface DeploymentBuild {
  Name: string;
  Tag: string;
  Branch: string;
  ImportURL: string;
}
export interface ReplicaStatus {
  /**
   * DesiredReplicas is the number of replicas that the deployment should have.
   */
  desiredReplicas: number /* int */;
  /**
   * ReadyReplicas is the number of replicas that are ready.
   */
  readyReplicas: number /* int */;
  /**
   * AvailableReplicas is the number of replicas that are available.
   */
  availableReplicas: number /* int */;
  /**
   * UnavailableReplicas is the number of replicas that are unavailable.
   */
  unavailableReplicas: number /* int */;
}
export interface DeploymentCreated {
  id: string;
  jobId: string;
}
export interface DeploymentDeleted {
  id: string;
  jobId: string;
}
export interface DeploymentUpdated {
  id: string;
  jobId?: string;
}
export interface CiConfig {
  config: string;
}
export interface DeploymentCommand {
  command: string;
}
export interface LogMessage {
  source: string;
  prefix: string;
  line: string;
  createdAt: string;
}

//////////
// source: discover.go

export interface DiscoverRead {
  version: string;
  roles: Role[];
}

//////////
// source: error.go

export interface BindingError {
  validationErrors: { [key: string]: string[]};
}

//////////
// source: job.go

export interface JobRead {
  id: string;
  userId: string;
  type: string;
  status: string;
  lastError?: string;
  createdAt: string;
  lastRunAt?: string;
  finishedAt?: string;
  runAfter?: string;
}
export interface JobUpdate {
  status?: string;
}

//////////
// source: notification.go

export interface NotificationRead {
  id: string;
  userId: string;
  type: string;
  content: { [key: string]: any};
  createdAt: string;
  readAt?: string;
  completedAt?: string;
}
export interface NotificationUpdate {
  read: boolean;
}

//////////
// source: resource_migration.go

export interface ResourceMigrationRead {
  id: string;
  /**
   * ResourceID is the ID of the resource that is being migrated.
   * This can be a VM ID, deployment ID, etc. depending on the type of the migration.
   */
  resourceId: string;
  /**
   * UserID is the ID of the user who initiated the migration.
   */
  userId: string;
  /**
   * Type is the type of the resource migration.
   * Possible values:
   * - updateOwner
   */
  type: string;
  /**
   * ResourceType is the type of the resource that is being migrated.
   * Possible values:
   * - vm
   * - deployment
   */
  resourceType: string;
  /**
   * Status is the status of the resource migration.
   * When this field is set to 'accepted', the migration will take place and then automatically be deleted.
   */
  status: string;
  /**
   * UpdateOwner is the set of parameters that are required for the updateOwner migration type.
   * It is empty if the migration type is not updateOwner.
   */
  updateOwner?: {
    ownerId: string;
  };
  createdAt: string;
  deletedAt?: string;
}
export interface ResourceMigrationCreate {
  /**
   * Type is the type of the resource migration.
   * Possible values:
   * - updateOwner
   */
  type: string;
  /**
   * ResourceID is the ID of the resource that is being migrated.
   * This can be a VM ID, deployment ID, etc. depending on the type of the migration.
   */
  resourceId: string;
  /**
   * Status is the status of the resource migration.
   * It is used by privileged admins to directly accept or reject a migration.
   * The field is ignored by non-admins.
   * Possible values:
   * - accepted
   * - pending
   */
  status?: string;
  /**
   * UpdateOwner is the set of parameters that are required for the updateOwner migration type.
   * It is ignored if the migration type is not updateOwner.
   */
  updateOwner?: {
    ownerId: string;
  };
}
export interface ResourceMigrationUpdate {
  /**
   * Status is the status of the resource migration.
   * It is used to accept a migration by setting the status to 'accepted'.
   * If the acceptor is not an admin, a Code must be provided.
   * Possible values:
   * - accepted
   * - pending
   */
  status: string;
  /**
   * Code is a token required when accepting a migration if the acceptor is not an admin.
   * It is sent to the acceptor using the notification API
   */
  code?: string;
}
export interface ResourceMigrationCreated extends ResourceMigrationRead {
  /**
   * JobID is the ID of the job that was created for the resource migration.
   * It will only be set if the migration was created with status 'accepted'.
   */
  jobId?: string;
}
export interface ResourceMigrationUpdated extends ResourceMigrationRead {
  /**
   * JobID is the ID of the job that was created for the resource migration.
   * It will only be set if the migration was updated with status 'accepted'.
   */
  jobId?: string;
}

//////////
// source: role.go

export interface Role {
  name: string;
  description: string;
  permissions: string[];
  quota?: Quota;
}

//////////
// source: sm.go

export interface SmDeleted {
  id: string;
  jobId: string;
}
export interface SmRead {
  id: string;
  ownerId: string;
  createdAt: string;
  zone: string;
  url?: string;
}

//////////
// source: status.go

export interface WorkerStatusRead {
  name: string;
  status: string;
  reportedAt: string;
}

//////////
// source: team.go

export interface TeamMember extends UserReadDiscovery {
  teamRole: string;
  memberStatus: string;
  joinedAt?: string;
  addedAt?: string;
}
export interface TeamResource {
  id: string;
  name: string;
  type: string;
}
export interface TeamMemberCreate {
  id: string;
  teamRole: string; // default to MemberRoleAdmin right now
}
export interface TeamMemberUpdate {
  id: string;
  teamRole: string; // default to MemberRoleAdmin right now
}
export interface TeamCreate {
  name: string;
  description: string;
  resources: string[];
  members: TeamMemberCreate[];
}
export interface TeamJoin {
  invitationCode: string;
}
export interface TeamUpdate {
  name?: string;
  description?: string;
  resources?: string[];
  members?: TeamMemberUpdate[];
}
export interface TeamRead {
  id: string;
  name: string;
  ownerId: string;
  description?: string;
  resources: TeamResource[];
  members: TeamMember[];
  createdAt: string;
  updatedAt?: string;
}

//////////
// source: user.go

export interface UserRead {
  id: string;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  publicKeys: PublicKey[];
  apiKeys: ApiKey[];
  userData: UserData[];
  role: Role;
  admin: boolean;
  quota: Quota;
  usage: Usage;
  storageUrl?: string;
  gravatarUrl?: string;
}
export interface UserReadDiscovery {
  id: string;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  gravatarUrl?: string;
}
export interface UserUpdate {
  publicKeys?: PublicKey[];
  /**
   * ApiKeys specifies the API keys that should remain. If an API key is not in this list, it will be deleted.
   * However, API keys cannot be created, use /apiKeys endpoint to create new API keys.
   */
  apiKeys?: ApiKey[];
  userData?: UserData[];
}
export interface UserData {
  key: string;
  value: string;
}
export interface PublicKey {
  name: string;
  key: string;
}
export interface ApiKey {
  name: string;
  createdAt: string;
  expiresAt: string;
}
export interface Quota {
  cpuCores: number /* float64 */;
  ram: number /* float64 */;
  diskSize: number /* float64 */;
  snapshots: number /* int */;
  gpuLeaseDuration: number /* float64 */; // in hours
}
export interface Usage {
  cpuCores: number /* float64 */;
  ram: number /* float64 */;
  diskSize: number /* int */;
}

//////////
// source: webhook.go

export interface HarborWebhook {
  type: string;
  occur_at: number /* int */;
  operator: string;
  event_data: {
    resources: {
      digest: string;
      tag: string;
      resource_url: string;
    }[];
    repository: {
      date_created: number /* int */;
      name: string;
      namespace: string;
      repo_full_name: string;
      repo_type: string;
    };
  };
}

//////////
// source: zone.go

export interface ZoneEndpoints {
  deployment?: string;
  storage?: string;
  vm?: string;
  vmApp?: string;
}
export interface ZoneRead {
  name: string;
  description: string;
  capabilities: string[];
  endpoints: ZoneEndpoints;
  legacy: boolean;
  enabled: boolean;
}
