// Code generated by client-gen. DO NOT EDIT.

package v1

type KubeVirtExpansion interface{}

type VirtualMachineExpansion interface{}

type VirtualMachineInstanceExpansion interface{}

type VirtualMachineInstanceMigrationExpansion interface{}

type VirtualMachineInstancePresetExpansion interface{}

type VirtualMachineInstanceReplicaSetExpansion interface{}
