// Code generated by tygo. DO NOT EDIT.

//////////
// source: deployment.go

export interface DeploymentGet {
  DeploymentID: string;
}
export interface DeploymentDelete {
  DeploymentID: string;
}
export interface DeploymentUpdate {
  DeploymentID: string;
}
export interface CiConfigGet {
  DeploymentID: string;
}
export interface DeploymentCommand {
  DeploymentID: string;
}
export interface LogsGet {
  DeploymentID: string;
}
export interface BuildGet {
  DeploymentID: string;
}

//////////
// source: job.go

export interface JobGet {
  JobID: string;
}
export interface JobUpdate {
  JobID: string;
}

//////////
// source: notification.go

export interface NotificationGet {
  NotificationID: string;
}
export interface NotificationUpdate {
  NotificationID: string;
}
export interface NotificationDelete {
  NotificationID: string;
}

//////////
// source: resource_migration.go

export interface ResourceMigrationGet {
  ResourceMigrationID: string;
}
export interface ResourceMigrationUpdate {
  ResourceMigrationID: string;
}
export interface ResourceMigrationDelete {
  ResourceMigrationID: string;
}

//////////
// source: sm.go

export interface SmGet {
  SmID: string;
}
export interface SmDelete {
  SmID: string;
}

//////////
// source: team.go

export interface TeamGet {
  TeamID: string;
}
export interface TeamUpdate {
  TeamID: string;
}

//////////
// source: user.go

export interface UserGet {
  UserID: string;
}
export interface UserUpdate {
  UserID: string;
}
export interface ApiKeyCreate {
  UserID: string;
}

//////////
// source: zone.go

export interface ZoneGet {
  Name: string;
  Type: string;
}
