// Code generated by tygo. DO NOT EDIT.

//////////
// source: common.go

export interface Pagination {
  Page: number /* int */;
  PageSize: number /* int */;
}
export interface SortBy {
  Field: string;
  Order: number /* int */;
}

//////////
// source: gpu_group.go

export interface GpuGroupList {
  Pagination?: Pagination;
}

//////////
// source: gpu_lease.go

export interface GpuLeaseList {
  Pagination?: Pagination;
  All: boolean;
  VmIDs: string[];
}
export interface GpuLeaseCreate {
  VmID: string;
}

//////////
// source: snapshot.go

export interface VmSnapshotList {
  Pagination?: Pagination;
}

//////////
// source: vm.go

export interface VmList {
  Pagination?: Pagination;
  All: boolean;
  UserID?: string;
}

//////////
// source: vm_action.go

export interface VmActionCreate {
  VmID: string;
}
