// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type VirtualMachineRestoreExpansion interface{}

type VirtualMachineSnapshotExpansion interface{}

type VirtualMachineSnapshotContentExpansion interface{}
