// Code generated by tygo. DO NOT EDIT.

//////////
// source: gpu_group.go

export interface GpuGroupList {
}
export interface GpuGroupGet {
  GpuGroupID: string;
}
export interface GpuGroupDelete {
  GpuGroupID: string;
}
export interface GpuGroupUpdate {
  GpuGroupID: string;
}

//////////
// source: gpu_lease.go

export interface GpuLeaseList {
}
export interface GpuLeaseGet {
  GpuLeaseID: string;
}
export interface GpuLeaseDelete {
  GpuLeaseID: string;
}
export interface GpuLeaseUpdate {
  GpuLeaseID: string;
}

//////////
// source: snapshot.go

export interface VmSnapshotCreate {
  VmID: string;
}
export interface VmSnapshotList {
  VmID: string;
}
export interface VmSnapshotGet {
  VmID: string;
  SnapshotID: string;
}
export interface VmSnapshotDelete {
  VmID: string;
  SnapshotID: string;
}

//////////
// source: vm.go

export interface VmGet {
  VmID: string;
}
export interface VmDelete {
  VmID: string;
}
export interface VmUpdate {
  VmID: string;
}
export interface GpuAttach {
  VmID: string;
  GpuID: string;
}
export interface GpuDetach {
  VmID: string;
}
export interface GpuGet {
  GpuID: string;
}
