// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go-deploy/pkg/imp/kubevirt/kubevirt/typed/snapshot/v1alpha1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSnapshotV1alpha1 struct {
	*testing.Fake
}

func (c *FakeSnapshotV1alpha1) VirtualMachineRestores(namespace string) v1alpha1.VirtualMachineRestoreInterface {
	return &FakeVirtualMachineRestores{c, namespace}
}

func (c *FakeSnapshotV1alpha1) VirtualMachineSnapshots(namespace string) v1alpha1.VirtualMachineSnapshotInterface {
	return &FakeVirtualMachineSnapshots{c, namespace}
}

func (c *FakeSnapshotV1alpha1) VirtualMachineSnapshotContents(namespace string) v1alpha1.VirtualMachineSnapshotContentInterface {
	return &FakeVirtualMachineSnapshotContents{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSnapshotV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
