name: Build types

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dto/**'
      - '.github/workflows/build-types.yml'

jobs:
  build-types:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Check for TS errors
      run: |
        cd export
        bun run tsc

    - name: Build types
      run: |       
        cd scripts
        chmod +x ./generate-types.sh
        ./generate-types.sh
        cd ..
      