// Code generated by go:generate with kthcloud/go-deploy/pkg/subsystems/k8s/api/cmd/structclone; DO NOT EDIT.

package nvidia

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type GpuConfig struct {
	v1.TypeMeta `json:",inline" bson:",inline"`
	Sharing     *GpuSharing `json:"sharing,omitempty" bson:"sharing,omitempty"`
}
