// Code generated by go:generate with kthcloud/go-deploy/pkg/subsystems/k8s/api/cmd/structclone; DO NOT EDIT.

package nvidia

type GpuSharing struct {
	Strategy          GpuSharingStrategy `json:"strategy"`
	TimeSlicingConfig *TimeSlicingConfig `json:"timeSlicingConfig,omitempty"`
	MpsConfig         *MpsConfig         `json:"mpsConfig,omitempty"`
}
