// Code generated by go:generate with kthcloud/go-deploy/pkg/subsystems/k8s/api/cmd/structclone; DO NOT EDIT.

package nvidia

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

type MpsConfig struct {
	DefaultActiveThreadPercentage     *int                         `json:"defaultActiveThreadPercentage,omitempty"`
	DefaultPinnedDeviceMemoryLimit    *resource.Quantity           `json:"defaultPinnedDeviceMemoryLimit,omitempty"`
	DefaultPerDevicePinnedMemoryLimit map[string]resource.Quantity `json:"defaultPerDevicePinnedMemoryLimit,omitempty"`
}
